Update German
contao/contao-manager pull request #677
Opened 2022-03-15 15:28 UTC by Justman10000

2022-03-16 08:45 UTC, fritzmg requested changes
Translations are managed on Transifex: https://www.transifex.com/contao/contao-manager/

You can request being part of the translation team there.

2022-03-16 08:45 UTC, fritzmg commented on src/i18n/de.json
> +    "ui.account.intro2": "Sollten Probleme auftreten, dann prüfe {ourGithubIssues}. Falls für dein Anliegen noch kein Ticket existiert, kannst du gern ein Neues erstellen.",
This change seems unnecessary.

2022-03-16 08:45 UTC, fritzmg commented on src/i18n/de.json
> +    "ui.task.failedDescription2": "Sollte dies wiederholt geschehen, wird dein Server möglicherweise nicht unterstützt.",
This change seems unecessary.

2022-03-17 07:19 UTC, aschempp commented
Thank you @Justman10000. As @fritzmg pointed out, translations are managed on Transifex. I like your improved wording and have adopted everything, it will be included in the next release.

2022-03-17 07:19 UTC, closed without merging